apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-consumer-topic2
  labels:
    app: pulsar-consumer-topic2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulsar-consumer-topic2
  template:
    metadata:
      labels:
        app: pulsar-consumer-topic2
    spec:
      containers:
      - name: pulsar-consumer
        image: rwaltertcd/pulsar-consumer:latest
        imagePullPolicy: Always
        env:
        - name: PULSAR_SERVICE_URL
          value: "pulsar://my-pulsar-broker.pulsar.svc.cluster.local:6650"
        - name: TOPIC
          value: "persistent://public/default/topic-2"
        - name: SUBSCRIPTION_NAME
          value: "subscription-topic2"
